pipeline {
    agent any 
    environment{
        AWS_DEFAULT_REGION='us-east-1'
    }
    stages {
        stage('Terraform init') {
            steps {
                withCredentials([aws(accessKeyVariable: 'AWS_ACCESS_Key_ID', credentialsId:'devops-role-access-setup', secretKeyVariable: 'AWS_SECRET_ACCESS_KEY') ]){
                    sh '''
                        /usr/local/bin/terraform version
                        /usr/local/bin/tfenv list
                        /usr/local/bin/tfenv use 1.3.1
                        cd /Users/nrkodari/git-repos/aws-labs/ec2
                        /usr/local/bin/terraform init
                    '''
                }
            }
        }
        stage('Terraform plan') {
            steps {
                sh '''
                    cd /Users/nrkodari/git-repos/aws-labs/ec2
                    /usr/local/bin/terraform plan
                '''
            }
        }
        stage('Terraform apply') {
            steps {
                sh '''
                    cd /Users/nrkodari/git-repos/aws-labs/ec2
                    /usr/local/bin/terraform apply -auto-approve
                '''
            }
        }
    }  
}

withCredentials([aws(accessKeyVariable: 'AWS_ACCESS_Key_ID', credentilsId:'devops-role-access-setup', secretKeyVariable: 'AWS_SECRET_ACCESS_KEY') ]) 
